dubbo:
  application:
    name: service-goods
  registry:
    address: zookeeper://cheeeg.com:2181
  protocol:
    port: -1
  consumer:
    check: false
    timeout: 10000
spring:
  datasource:
    url: jdbc:mysql:///shopgoods?serverTimezone=GMT%2B8
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver

  #配置RabbitMQ
  rabbitmq:
    host: 192.168.184.222
    username: guest
    password: guest
    virtual-host: /
    port: 5672


mybatis-plus:
  mapper-locations: classpath:com/cy/dao/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl