server:
  port: 8080

spring:
  thymeleaf:
    cache: false
dubbo:
  registry:
    address: zookeeper://cheeeg.com:2181
  consumer:
    check: false
    timeout: 10000
  application:
    name: web-goodse

fdfs:
  pool:
    jmx-enabled: false
  thumb-image:
    width: 100
    height: 100
  tracker-list:
    #    - 192.168.184.222:22122
    - cheeeg.com:22122

