dubbo:
  protocol:
    port: -1
  registry:
    address: zookeeper://cheeeg.com:2181
  application:
    name: shop-user
  consumer:
    check: false
    timeout: 5000
spring:
  datasource:
    url: jdbc:mysql:///shopgoods?serverTimezone=GMT%2B8
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
