dubbo:
  registry:
    address: zookeeper://cheeeg.com:2181
  protocol:
    port: -1
  application:
    name: shop_searchservice
  consumer:
    check: false

#配置solr   → .../solr(固定写法)/mycollection(指向solr的索引库)
spring:
  data:
    solr:
      host: http://192.168.184.222:8983/solr/mycollection

  #配置RabbitMQ
  rabbitmq:
    host: 192.168.184.222
    username: guest
    password: guest
    virtual-host: /
    port: 5672
